spring:
  application:
    name: ticket-booking

  datasource:
    url: jdbc:postgresql://localhost:5433/ticket_booking
    username: ticket_user
    password: ticket_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:this-is-a-very-long-secret-key-for-ticket-booking-system-at-least-32-bytes}
    expiration_ms: ${EXPIRATION_TIME_MS:86400000}