spring:
  application:
    name: ticket-booking

  datasource:
    url: jdbc:postgresql://localhost:5433/ticket_booking
    username: ticket_user
    password: ticket_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ticket-order-consumer-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.yuqing.ticketbooking.*"
        spring.json.value.default.type: com.yuqing.ticketbooking.messaging.OrderCreatedMessage
        spring.json.use.type.headers: false
    producer:
      properties:
        spring.json.add.type.headers: false


server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:this-is-a-very-long-secret-key-for-ticket-booking-system-at-least-32-bytes}
    expiration_ms: ${EXPIRATION_TIME_MS:86400000}
