spring:
  application:
    name: ticket-booking

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:ticket_booking}
    username: ${DB_USERNAME:ticket_user}
    password: ${DB_PASSWORD:ticket_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ticket-order-consumer-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.yuqing.ticketbooking.*"
        spring.json.value.default.type: com.yuqing.ticketbooking.messaging.OrderCreatedMessage
        spring.json.use.type.headers: false
    producer:
      properties:
        spring.json.add.type.headers: false


server:
  port: ${SERVER_PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:this-is-a-very-long-secret-key-for-ticket-booking-system-at-least-32-bytes}
    expiration_ms: ${EXPIRATION_TIME_MS:86400000}
